consumer_key: CONSUMER_KEY
consumer_secret: CONSUMER_SECRET
access_key: ACCESS_KEY
access_secret: ACCESS_SECRET
check_interval: TIME_IN_SECONDS
paid_upload_speed: EXPECTED_UPLOAD
paid_download_speed: EXPECTED_DOWNLOAD